from selenium import webdriver
import time
from selenium.webdriver.common.action_chains import ActionChains


driver = webdriver.Chrome()
driver.get("http://localhost:8080/HKR/")
driver.maximize_window()
# driver.find_element_by_xpath("//*[@id  = 'loginname' and @type='text']").send_keys("aaaaa")
# driver.find_element_by_xpath("//*[@id='password' and @type='password']").send_keys("aaaaa")
# driver.find_element_by_xpath("//*[@id='submit' and @type='submit']").click()
# time.sleep(2)
# #  换头像
# driver.find_element_by_xpath("//*[@id='img' and @title='点击更换头像']").click()
# time.sleep(2)
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[3]/ul/li[8]").click()
# time.sleep(2)
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[4]/form/div[2]/input").send_keys(r"D:\Python学习\day16\美女.jpg")
# driver.find_element_by_xpath("//*[@id='pic_btn' and @value='pic_btn']").click()
# time.sleep(2)
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div[3]/ul/li[2]/a[2]").click()
# time.sleep(2)
# driver.find_element_by_xpath("//*[@class='show_tea' and @name='time']").send_keys("7")
# driver.find_element_by_xpath("//*[@class='show_tea' and @name='teaName']").send_keys("贾生")
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[5]/td[3]/div/label[2]").click()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[6]/td[2]/div/label[2]").click()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[7]/td[3]/div/label[1]") .click()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[8]/td[2]/div/label[2]").click()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[9]/td[2]/div/label[2]") .click()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[10]/td[3]/div/label[2]").click()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[11]/td[2]/div/label[2]") .click()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div/div/div/form/table/tbody/tr[12]/td[2]/div/label[2]").click()
# driver.find_element_by_xpath("//*[@id='textarea' and @name='suggestion']").send_keys("无")
# driver.find_element_by_xpath("//*[@id='subtn' and @class='login-button']").click()
# time.sleep(2)
# driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[2]/li[1]/ul/li/div/span[4]/a").click()
# driver.find_element_by_xpath("//*[@name='loginname' and @type='text']").clear()
# driver.find_element_by_xpath("//*[@name='loginname' and @type='text']").send_keys("aaa")
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/center/div/form/table/tbody/tr[3]/td[2]/input").clear()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/center/div/form/table/tbody/tr[3]/td[2]/input").send_keys("aaa")
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/center/div/form/table/tbody/tr[4]/td[2]/span/input[1]").clear()
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/center/div/form/table/tbody/tr[4]/td[2]/span/input[1]").send_keys("55")
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/center/div/form/table/tbody/tr[5]/td[2]/select").send_keys("男")
# driver.find_element_by_xpath("//*[@name='address' and @type='text']").clear()
# driver.find_element_by_xpath("//*[@name='address' and @type='text']").send_keys("你家")
# driver.find_element_by_xpath("//*[@name='email' and @type='text']").clear()
# driver.find_element_by_xpath("//*[@name='email' and @type='text']").send_keys("484669732@163.com")
# driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/center/div/form/table/tbody/tr[9]/td[2]/textarea").send_keys("无")
# driver.find_element_by_xpath("//*[@id='btn_modify' and @class='login-button']").click()
# time.sleep(2)
# driver.find_element_by_xpath("//*[@class='tabs-close']").click()
# driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[2]/li[2]/ul/li/div/span[4]").click()
# time.sleep(2)
# driver.find_element_by_xpath("//*[@class='tabs-close']").click()
# time.sleep(2)
# driver.find_element_by_xpath("/html/body/div[2]/div/div/a[2]/img").click()
# time.sleep(1)
# driver.quit()

#教师登录
driver.find_element_by_xpath("/html/body/div/div/div[1]/div[2]/a[2]").click()
driver.find_element_by_xpath("/html/body/div/div/div/form/div/input[2]").send_keys("jason")
driver.find_element_by_xpath("/html/body/div/div/div/form/div/input[3]").send_keys("admin")
driver.find_element_by_xpath("//*[@id='submit' and @type='submit']").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[3]/div[2]/div/li[1]/ul/li[1]/div/span[4]/a").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div/div[1]/table/tbody/tr/td[1]/a/span/span/input").send_keys("李艳")
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div/div[1]/table/tbody/tr/td[2]/a").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[9]/div/a").click()
time.sleep(1)
driver.switch_to.alert.accept()
time.sleep(1)
driver.find_element_by_xpath("//*[@class='tabs-close']").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[3]/div[2]/div/li[1]/ul/li[2]/div/span[4]/a").click()
time.sleep(1)
driver.find_element_by_xpath("//*[@id='J-stu']").send_keys("jason")
driver.find_element_by_xpath("//*[@id='J-phone']").send_keys("13452353456")
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div/div[1]/table/tbody/tr/td[4]/a/span").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[11]/div").click()
driver.find_element_by_xpath("/html/body/div[8]/div[3]/a").click()
time.sleep(1)
driver.find_element_by_xpath("//*[@class='tabs-close']").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[3]/div[2]/div/li[1]/ul/li[3]/div/span[4]").click()
time.sleep(1)
driver.find_element_by_xpath("//*[@id='course_panel']/div/div/div[1]/table/tbody/tr/td/a/span/span[1]").click()
driver.find_element_by_xpath("//*[@id='course_form_add']/table/tbody/tr[1]/td[2]/input").send_keys("1111")
driver.find_element_by_xpath("//*[@id='course_form_add']/table/tbody/tr[2]/td[2]/textarea").send_keys("没基础学习")
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[7]/div[3]/a[1]/span").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[10]/div[3]/a").click()
time.sleep(1)
driver.find_element_by_xpath("//*[@id='course_panel']/div/div/div[1]/table/tbody/tr/td/a/span").click()
time.sleep(1)
driver.find_element_by_xpath("/html/body/div[7]/div[3]/a[2]/span").click()
time.sleep(1)
driver.find_element_by_xpath("//*[@class='tabs-close']").click()








